// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	context "context"

	events "github.com/aws/aws-lambda-go/events"
	mock "github.com/stretchr/testify/mock"
)

// Event is an autogenerated mock type for the Event type
type Event struct {
	mock.Mock
}

// Handler provides a mock function with given fields: ctx, event
func (_m *Event) Handler(ctx context.Context, event events.S3Event) (events.S3Event, error) {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Handler")
	}

	var r0 events.S3Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, events.S3Event) (events.S3Event, error)); ok {
		return rf(ctx, event)
	}
	if rf, ok := ret.Get(0).(func(context.Context, events.S3Event) events.S3Event); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Get(0).(events.S3Event)
	}

	if rf, ok := ret.Get(1).(func(context.Context, events.S3Event) error); ok {
		r1 = rf(ctx, event)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEvent creates a new instance of Event. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEvent(t interface {
	mock.TestingT
	Cleanup(func())
}) *Event {
	mock := &Event{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
