run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 2
  tests: true
  skip-dirs:
    - /internal/test

  enable:
    - staticcheck
    - revive
    - govet
    - errcheck
    - gosec
    - dupl

    - gocritic
    - prealloc

    - stylecheck
    - goconst
    - gofmt
    - tagliatelle

  linters-settings:
    errcheck:
      check-type-assertions: true

    dupl:
      threshold: 100
