version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      DATABASE_URL: "mongodb://mongo:27017/telemetry"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY: "your-access-key"
      AWS_SECRET_KEY: "your-secret-key"
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
