// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	models "github/desafio/models"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// InsertGPSData provides a mock function with given fields: data
func (_m *Repository) InsertGPSData(data models.GPS) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for InsertGPSData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(models.GPS) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertGyroscopeData provides a mock function with given fields: data
func (_m *Repository) InsertGyroscopeData(data models.Gyroscope) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for InsertGyroscopeData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(models.Gyroscope) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertPhoto provides a mock function with given fields: data
func (_m *Repository) InsertPhoto(data models.Photo) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for InsertPhoto")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(models.Photo) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
