// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AdapterInterface is an autogenerated mock type for the AdapterInterface type
type AdapterInterface struct {
	mock.Mock
}

// Value provides a mock function with given fields:
func (_m *AdapterInterface) Value() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Value")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// NewAdapterInterface creates a new instance of AdapterInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdapterInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdapterInterface {
	mock := &AdapterInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
