@baseUrl = http://localhost:3000

# @name create_gps
POST {{baseUrl}}/telemetry/gps
Content-Type: application/json

{
    "latitude": 28.99,
    "longitude": -491.99
}

###

# @name create_gyroscope
POST {{baseUrl}}/telemetry/gyroscope
Content-Type: application/json

{
    "x": -192.4,
    "y": 99.0,
    "z": 12.944
}
